"""
Django settings for VulnScan vulnerability scanner project.

This configuration file contains all settings for the VulnScan Django project.
The application is an educational vulnerability scanning platform with 
React frontend and Django REST API backend.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see:
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# =============================================================================
# PATH CONFIGURATION
# =============================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file for secure configuration management
load_dotenv()

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
# In production, this should be set via environment variable
SECRET_KEY = 'django-insecure-6b=-d0g%2rrw_a4@h3w*nhc!%967(!t@it@fxt0+!@q=n+%08h'

# SECURITY WARNING: don't run with debug turned on in production!
# Debug mode should be False in production for security
DEBUG = True

# Hosts/domain names that this Django site can serve
# In production, specify exact hosts instead of wildcard
ALLOWED_HOSTS = ["*"]

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================

# PostgreSQL database configuration for Neon serverless PostgreSQL
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),          # Database name from environment
        "USER": os.getenv("DB_USER"),          # Database user from environment
        "PASSWORD": os.getenv("DB_PASSWORD"),  # Database password from environment
        "HOST": os.getenv("DB_HOST"),          # Database host from environment
        "PORT": os.getenv("DB_PORT", "5432"),  # Database port (default: 5432)
        "OPTIONS": {
            "sslmode": os.getenv("DB_SSLMODE", "require"),  # SSL requirement for secure connection
        },
    }
}

# Alternative database configuration using DATABASE_URL (commented out)
# Uncomment this section if using a single DATABASE_URL environment variable
"""
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    # Fallback to individual environment variables with SSL enforcement
    DB_NAME = os.getenv("DB_NAME", "neondb")
    DB_USER = os.getenv("DB_USER", "")
    DB_PASSWORD = os.getenv("DB_PASSWORD", "")
    DB_HOST = os.getenv("DB_HOST", "")
    DB_PORT = os.getenv("DB_PORT", "5432")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": DB_HOST,
            "PORT": DB_PORT,
            "OPTIONS": {
                "sslmode": os.getenv("DB_SSLMODE", "require"),
            },
        }
    }
"""

# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

# Django applications installed in this project
INSTALLED_APPS = [
    # Django core applications
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party applications
    'django.contrib.postgres',   # PostgreSQL-specific features
    "rest_framework",            # Django REST Framework for API
    
    # Project-specific applications
    "apps.auth_app",             # Custom authentication application
    "apps.scans_app",            # Vulnerability scanning application
]

# Middleware classes - processed in order for each request
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',        # Security enhancements
    'django.contrib.sessions.middleware.SessionMiddleware', # Session management
    'django.middleware.common.CommonMiddleware',            # URL normalization
    'django.middleware.csrf.CsrfViewMiddleware',            # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware', # User authentication
    'django.contrib.messages.middleware.MessageMiddleware', # Message framework
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Clickjacking protection
]

# Root URL configuration
ROOT_URLCONF = 'vulnscanner.urls'

# Template configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Additional template directories
        'APP_DIRS': True,                  # Search for templates in app directories
        'OPTIONS': {
            'context_processors': [
                # Context processors add variables to all templates
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application for deployment
WSGI_APPLICATION = 'vulnscanner.wsgi.application'

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

# Password validation rules for enhanced security
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

# Language and timezone settings
LANGUAGE_CODE = 'en-us'      # Default language
TIME_ZONE = 'UTC'           # Default timezone
USE_I18N = True             # Enable internationalization
USE_TZ = True               # Enable timezone support

# =============================================================================
# STATIC FILES CONFIGURATION
# =============================================================================

# URL prefix for static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type for models
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# CELERY CONFIGURATION
# =============================================================================

# Celery configuration for asynchronous task processing
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")        # Redis as message broker
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/1") # Redis as result backend

# Task routing configuration - specific queues for different task types
CELERY_TASK_ROUTES = {
    "apps.scans_app.tasks.run_scan_task": {"queue": "scans"},  # Route scan tasks to 'scans' queue
}

# Task execution limits for resource management
CELERY_TASK_TIME_LIMIT = 60 * 15      # Maximum time a task can run (15 minutes)
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 10 # Soft time limit before task is interrupted (10 minutes)

# Serialization configuration
CELERY_ACCEPT_CONTENT = ["json"]      # Accept only JSON content
CELERY_TASK_SERIALIZER = "json"       # Serialize tasks as JSON
CELERY_RESULT_SERIALIZER = "json"     # Serialize results as JSON

# =============================================================================
# MEDIA FILES CONFIGURATION
# =============================================================================

# Media files configuration for user uploads (avatars, reports, etc.)
MEDIA_URL = "/media/"                 # URL prefix for media files
MEDIA_ROOT = BASE_DIR / "media"       # Filesystem path for media storage
